# Generated by Django 4.2 on 2023-05-13 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='pic',
            field=models.FileField(default='sad.png', upload_to='seller_pics'),
        ),
    ]
