# Generated by Django 4.2 on 2023-05-15 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0003_sellerorderhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerorderhistory',
            name='status',
            field=models.CharField(choices=[('order placed', 'order placed'), ('out for delivery', 'out for delivery')], default='order placed', max_length=150),
        ),
    ]
